import { contextBridge } from 'electron';
import { createYomitomoDesktopApi } from './desktop-api-fragments';

export type {
  AppInfo,
  AgentRuntimeTraceEntry,
  AgentRuntimeTraceListInput,
  AgentRuntimeTraceTaskType,
  AppLockSetEnabledInput,
  AppLockSetLockedInput,
  AppLockSetPinInput,
  AppLockSetShortcutInput,
  AppLockStatus,
  AppLockUnlockInput,
  AppLockVerifyPinInput,
  AppLockVerifyPinResult,
  AddCollectionMembersInput,
  AnnotationDiscussionWindowOpenInput,
  AnnotationDiscussionWindowOpenResult,
  AnnotationDiscussionWindowState,
  AnnotationDiscussionWindowStateEvent,
  AnnotationDiscussionWindowsCloseArticleInput,
  AnnotationDiscussionWindowsCloseArticleResult,
  AnnotationSedimentationWindowOpenInput,
  AnnotationSedimentationWindowOpenResult,
  AnnotationSedimentationCommitInput,
  AnnotationSedimentationCommitResult,
  AnnotationDistillationCommitTransition,
  AnnotationDistillationCommittedEvent,
  AssistantExecutionQueryInput,
  AssistantExecutionRunDetail,
  AssistantExecutionRunListItem,
  AssistantExecutionRun,
  AssistantExecutionStatus,
  AssistantExecutionSummary,
  AssistantExecutionSummaryGroup,
  AssistantExecutionTotals,
  AssistantExecutionUsage,
  ArticleAnnotationDeleteInput,
  ArticleAnnotationUpsertInput,
  ArticleCommentDeleteInput,
  ArticleCommentUpsertInput,
  ArticleImportResult,
  ArticleImportUrlInput,
  ArticleLibraryListInput,
  ArticleLibraryListResult,
  ArticleLibrarySource,
  ArticleLibrarySourceCounts,
  ArticleReaderChatStateSaveInput,
  CreateCollectionInput,
  CreateCollectionResult,
  DataManagementPathKind,
  DataManagementPaths,
  DatabaseBackupResult,
  DatabaseRestoreResult,
  EbookImportFileInput,
  PerformanceTimingInput,
  PdfImportFileInput,
  RemoveCollectionMemberInput,
  RenameCollectionInput,
  SetLibraryPinInput,
  WeReadOpenTarget,
  WeReadReadingStatsQueryInput,
  WeReadSaveSettingsInput,
} from '../ipc-contract';

const preloadLoadedAt = performance.now();

const api = createYomitomoDesktopApi({
  platform: process.platform,
  preloadLoadedAt,
});

contextBridge.exposeInMainWorld('yomitomoDesktop', api);

export type YomitomoDesktopApi = typeof api;
