packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  sharp: true
  spawn-sync: true
  workerd: true
peerDependencyRules:
  allowedVersions:
    "electron-vite@5>vite": "8"
