import { describe, expect, it } from 'vitest';
import * as corePublicApi from './index';

const coreRuntimeExports = [
  'activeReadingMemoryEntries',
  'alphaColor',
  'annotationColor',
  'annotationDensityInstruction',
  'annotationDensityMax',
  'annotationHasPublishedDistillation',
  'annotationIdsAtHighlightPoint',
  'annotationPersona',
  'annotationPrimaryComment',
  'annotationStoredColor',
  'annotationThoughtComments',
  'annotationThreadComments',
  'annotationToPublicAgent',
  'annotationTypeLabel',
  'annotationTypeLabels',
  'appendAnnotationComment',
  'applySupersededEntryFilter',
  'articlePublishedDistillationCount',
  'articleTitleTocItems',
  'buildCurrentChapterLexicalRelatedPassages',
  'buildEpubBookIndex',
  'buildHighlightSegments',
  'buildReadingContextBundle',
  'buildTocAnnotationStats',
  'commentPersona',
  'computeReadingActivityDays',
  'computeReadingStats',
  'createAgentAnnotation',
  'createEpubTextAnchor',
  'createEpubTextAnchorFromQuote',
  'createLexicalRelatedPassageCache',
  'createUserAnnotation',
  'createUserComment',
  'cursorPositionFromOffset',
  'deleteAnnotationComment',
  'epubIndexText',
  'extractTocItems',
  'findCurrentTocTarget',
  'findMentionedAgents',
  'findReaderSearchMatches',
  'getArticleSelection',
  'getMentionQuery',
  'highlightSegmentStyle',
  'highlightStyle',
  'inlineArticleFavicon',
  'inlineArticleImages',
  'isPrimaryTocItem',
  'isRangeInsideArticle',
  'locateEpubOffset',
  'locateEpubTextAnchor',
  'mergeReadingMemory',
  'normalizeAnnotationType',
  'normalizeReadingMemoryEntry',
  'offsetFromArticleStart',
  'parseAnnotationSuggestions',
  'performanceElapsedMs',
  'performanceStart',
  'rangeFromOffsets',
  'rangeHighlightBoxes',
  'readingContextTextForRange',
  'readingMemoryAnchorCheckpointEntries',
  'readingMemoryEntriesFromAnnotationThread',
  'readingMemoryEntriesFromMemoryDelta',
  'readingMemoryEntryFromAnnotation',
  'readingMemoryEntryFromComment',
  'readingMemoryEntrySearchText',
  'readingMemoryFromEntries',
  'readingMemoryViewRequestForAnnotatePayload',
  'readingMemoryViewRequestForMessagePayload',
  'replaceMentionQuery',
  'resolveEpubTextAnchor',
  'scrollReaderSurfaceToElement',
  'scrollReaderSurfaceToRect',
  'segmentAnnotationSpoilerPolicy',
  'selectionActionPosition',
  'selectionAnnotationSpoilerPolicy',
  'selectionThreadSpoilerPolicy',
  'sortAnnotations',
  'sortArticles',
  'timestamp',
  'updateAnnotationComment',
  'wholeBookSpoilerPolicy',
];

describe('core public surface', () => {
  it('keeps runtime exports explicit and reviewed', () => {
    const runtimeExports = Object.keys(corePublicApi);

    expect(runtimeExports).toHaveLength(coreRuntimeExports.length);
    expect(new Set(runtimeExports)).toEqual(new Set(coreRuntimeExports));
  });
});
