import { describe, expect, it } from 'vitest';
import { normalizeExternalUrlForOpen } from './external-url';

describe('external url boundary', () => {
  it('keeps HTTP and HTTPS links openable', () => {
    expect(normalizeExternalUrlForOpen('https://example.com/docs')).toBe(
      'https://example.com/docs',
    );
    expect(normalizeExternalUrlForOpen('http://example.com/docs')).toBe('http://example.com/docs');
  });

  it('allows the WeRead deeplink targets generated by the app', () => {
    expect(normalizeExternalUrlForOpen('weread://reading?bId=book_1')).toBe(
      'weread://reading?bId=book_1',
    );
    expect(normalizeExternalUrlForOpen('weread://bestbookmark?bookId=book_1')).toBe(
      'weread://bestbookmark?bookId=book_1',
    );
  });

  it('rejects unsupported WeRead deeplink targets', () => {
    expect(() => normalizeExternalUrlForOpen('weread://settings?token=secret')).toThrow(
      'Unsupported WeRead link target',
    );
    expect(() => normalizeExternalUrlForOpen('weread://reading.evil?bId=book_1')).toThrow(
      'Unsupported WeRead link target',
    );
    expect(() => normalizeExternalUrlForOpen('weread://reading:443?bId=book_1')).toThrow(
      'Unsupported WeRead link target',
    );
    expect(() => normalizeExternalUrlForOpen('weread://user@reading?bId=book_1')).toThrow(
      'Unsupported WeRead link target',
    );
    expect(() => normalizeExternalUrlForOpen('weread://reading/extra?bId=book_1')).toThrow(
      'Unsupported WeRead link target',
    );
  });

  it('rejects unsupported schemes', () => {
    expect(() => normalizeExternalUrlForOpen('file:///tmp/secret')).toThrow(
      'Only HTTP, HTTPS, and WeRead links are supported',
    );
  });
});
