export {
  cleanEpubDisplayTitle,
  cleanEpubFileNameTitle,
  defaultLibraryContentSourceOrder,
  EPUB_TITLE_CLEANUP_VERSION,
  normalizeAssistantExecutionMode,
  normalizeLibraryContentSources,
  normalizeSoundEffectsVolume,
  normalizeUiLanguage,
} from './types';
export type {
  Agent,
  AgentAnnotatePayload,
  AgentAnnotateResult,
  AgentAnnotationDensity,
  AgentContext,
  AgentDistillationReviewPayload,
  AgentKind,
  AgentMentionAction,
  AgentMentionDirective,
  AgentMentionInstruction,
  AgentMentionInstructionPayload,
  AgentMentionRoutePlan,
  AgentMessagePayload,
  AgentPersonality,
  AgentPersonalityPresentation,
  AgentReadingIntent,
  AgentReadingPlanItem,
  AgentReadingPlanMessage,
  AgentReviewPayload,
  AgentRoleCard,
  Annotation,
  AnnotationAuthor,
  AnnotationConfidence,
  AnnotationDistillation,
  AnnotationDistillationProposal,
  AnnotationDistillationProposalKind,
  AnnotationDistillationProposalStatus,
  AnnotationDistillationReviewFindingCategory,
  AnnotationDistillationReviewFindingItem,
  AnnotationDistillationReviewFindingSeverity,
  AnnotationDistillationReviewItem,
  AnnotationDistillationReviewMessage,
  AnnotationDistillationReviewOverviewItem,
  AnnotationDistillationReviewProposalItem,
  AnnotationDistillationReviewSession,
  AnnotationDistillationReviewStance,
  AnnotationDistillationStatus,
  AnnotationDraftKind,
  AnnotationEvidenceSource,
  AnnotationLightweightDraft,
  AnnotationMove,
  AnnotationSummary,
  AnnotationType,
  AppSettings,
  ArticleDeletePatch,
  ArticleReaderChatStatePatch,
  ArticleReadingProgress,
  ArticleReadingProgressPatch,
  ArticleRecord,
  ArticleSourceType,
  ArticleStorePatch,
  ArticleSummaryRecord,
  ArticleTranslation,
  ArticleTranslationDeleteRequest,
  ArticleTranslationRequest,
  ArticleTranslationSegment,
  ArticleTranslationSourceBlockInput,
  ArticleTranslationStatus,
  ArticleUpsertPatch,
  BilingualTranslationStyle,
  BilingualTranslationTargetLanguage,
  AssistantExecutionMode,
  AssistantRuntimeProgressEvent,
  AssistantRuntimeProgressStep,
  AssistantRuntimeProgressStepStatus,
  AssistantRuntimeProgressSummary,
  BaseReadingContext,
  BookContext,
  BudgetPolicy,
  ChapterDescriptor,
  ChapterMemory,
  ChapterRouteContext,
  ChapterTrace,
  Collection,
  CollectionMember,
  CollectionMembersPatch,
  CollectionDeletePatch,
  CollectionStorePatch,
  CollectionUpsertPatch,
  CollectionWithMembers,
  Comment,
  ContentRef,
  ContentRefKind,
  ContextSourceLabel,
  ContextSourceType,
  DedupContext,
  DesktopStore,
  EbookChapterRecord,
  EbookFormat,
  EbookMetadata,
  EbookRecord,
  EbookSummaryRecord,
  EpubBookIndex,
  EpubChapterIndex,
  EpubParagraphIndex,
  EpubSegmentIndex,
  EpubTitleCleanupInput,
  EvidencePolicy,
  FocusCoReadingMessage,
  FocusCoReadingPlan,
  FocusCoReadingSectionPlan,
  LibraryContentSourceId,
  LibraryContentSourcePreference,
  LibraryPin,
  LibraryPinPatch,
  LibraryPinTargetKind,
  LlmProvider,
  LocationContext,
  MemoryViewType,
  MessageSendShortcut,
  ParagraphWindow,
  PdfMetadata,
  PdfRecord,
  PdfRect,
  PdfTextAnchor,
  ProviderModel,
  ProviderModelInputMode,
  ProviderPreset,
  ProviderPresetId,
  ProviderType,
  PublicAgent,
  ReaderChatMessage,
  ReaderChatSession,
  ReaderChatState,
  ReaderProgress,
  ReaderQuestionContext,
  ReadingContextTask,
  ReadingMemory,
  ReadingMemoryAnchorPayload,
  ReadingMemoryCorrectionPayload,
  ReadingMemoryEntry,
  ReadingMemoryEntryKind,
  ReadingMemoryEntryPayload,
  ReadingMemoryProjection,
  ReadingMemoryScope,
  ReadingMemorySourceType,
  ReadingMemorySummaryPayload,
  ReadingMemoryTracePayload,
  ReadingMemoryView,
  ReadingMemoryViewEntry,
  ReadingMemoryViewEntrySource,
  ReadingMemoryVisibility,
  ReadingTaskContext,
  ReadingTrace,
  ReadingTraceScope,
  ReasoningEffort,
  RelatedPassage,
  RelatedPassageInput,
  RelatedPassageSource,
  ReleaseNoteAudience,
  ReleaseNoteHighlight,
  ReleaseNoteHighlightType,
  ReviewOpinionLabel,
  SegmentAnnotationContext,
  SegmentMemory,
  SegmentText,
  SegmentTraceMemory,
  SelectionActionShortcuts,
  SelectionAnnotationContext,
  SelectionThreadContext,
  SourceLabeledContextBlock,
  SpoilerAllowedScope,
  SpoilerPolicy,
  TextAnchor,
  TextRange,
  TextSourceFormat,
  TextSourceMetadata,
  TextSummary,
  TextSummaryScope,
  ThreadContext,
  ThreadMessageContext,
  TraceItem,
  TraceItemType,
  UiLanguage,
  UserFacingReleaseNote,
  UserProfile,
  WeReadBook,
  WeReadBookDetail,
  WeReadChapter,
  WeReadHighlight,
  WeReadOpenMethod,
  WeReadReadingStats,
  WeReadReadingStatsBook,
  WeReadReadingStatsItem,
  WeReadReadingStatsMode,
  WeReadReadingStatsSnapshot,
  WeReadReadingStatsState,
  WeReadSettings,
  WeReadSyncMode,
  WeReadSyncResult,
  WeReadThought,
  WeReadUser,
} from './types';

export {
  defaultMessageSendShortcut,
  defaultSelectionActionShortcuts,
  normalizeMessageSendShortcut,
  normalizeSelectionActionShortcutDraft,
  normalizeSelectionActionShortcutKey,
  normalizeSelectionActionShortcuts,
  selectionActionShortcutsConflict,
} from './shortcuts';

export { providerPresets } from './providers/providers';

export {
  agentPersonalityName,
  agentReadingIntentDisplayLabel,
  agentReadingIntentIcon,
  agentReadingIntentLabel,
  agentReadingIntentOptions,
  customPersonality,
  customPersonalityId,
  findAgentPersonalityId,
  normalizeAgentReadingIntent,
  normalizeAnnotationConfidence,
  normalizeAnnotationEvidenceSource,
  normalizeAnnotationMove,
  normalizeAnnotationType,
  normalizeReviewOpinionLabel,
  reviewOpinionLabels,
  reviewOpinionLabelTone,
} from './agents/agents';
export type { ReviewOpinionLabelTone } from './agents/agents';

export { normalizeTraceItemType } from './trace';

export { hashText, makeId } from './ids';

export {
  createPdfTextAnchor,
  createTextAnchor,
  isPdfTextAnchor,
  resolveTextAnchor,
  textAnchorQuoteHash,
} from './text-anchor';

export { renderMarkdown } from './markdown';

export { formatDateTimeValue, relativeTimeParts } from './date-time';
export type { RelativeTimeParts, RelativeTimeUnit } from './date-time';

export {
  compareVersions,
  selectHighlights,
  shouldShowAfterUpdate,
} from './release-notes/release-note';
export type { ReleaseNoteScene } from './release-notes/release-note';

export {
  agentPersonalityCore,
  agentPersonalityPresentations,
  defaultAgentPersonalityLocale,
  englishAgentPersonalityPresentations,
  localizedAgentPersonalities,
  localizedAgentPersonalitiesForKind,
  localizedAgentPersonality,
  resolveAgentPersonalityPresentation,
  resolveAgentPresetId,
  resolveAgentPublicIdentity,
  resolvePromptAgentIdentity,
  zhAgentPersonalityPresentations,
} from './agents/agent-presentations';

export {
  agentPersonalities,
  agentPersonalitiesForKind,
  annotationAgentPersonalities,
  reviewAgentPersonalities,
  readingPartnerSoul,
} from './agents/agent-presets';

export { readingPartnerSoul as defaultAgentSoul } from './agents/agent-presets';
