import type { ProviderPreset } from '../types';

export const providerPresets: ProviderPreset[] = [
  {
    id: 'dashscope',
    name: '阿里云百炼',
    type: 'openai-chat',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    modelName: 'qwen3.5-plus',
    logo: 'bailian.png',
    modelNames: [
      'qwen3.5-plus',
      'qwen3.5-flash',
      'qwen3-max',
      'kimi-k2.5',
      'glm-5',
      'deepseek-v3.2',
    ],
  },
  {
    id: 'deepseek',
    name: '深度求索',
    type: 'openai-chat',
    baseUrl: 'https://api.deepseek.com',
    modelName: 'deepseek-chat',
    logo: 'deepseek.png',
    modelNames: ['deepseek-chat', 'deepseek-reasoner'],
  },
  {
    id: 'moonshot',
    name: '月之暗面',
    type: 'openai-chat',
    baseUrl: 'https://api.moonshot.cn',
    modelName: 'moonshot-v1-auto',
    logo: 'moonshot.webp',
    modelNames: [
      'moonshot-v1-auto',
      'kimi-k2.5',
      'kimi-k2.6',
      'kimi-k2-thinking',
      'kimi-k2-turbo-preview',
    ],
  },
  {
    id: 'zhipu',
    name: '智谱开放平台',
    type: 'openai-chat',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    modelName: 'glm-5',
    logo: 'zhipu.png',
    modelNames: ['glm-5', 'glm-4.7', 'glm-4.6', 'glm-4.5', 'glm-4.5-flash'],
  },
  {
    id: 'doubao',
    name: '火山引擎',
    type: 'openai-chat',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    modelName: 'doubao-seed-1-8-251228',
    logo: 'volcengine.png',
    modelNames: [
      'doubao-seed-1-8-251228',
      'doubao-seed-2-0-pro-260215',
      'doubao-seed-2-0-lite-260215',
      'doubao-1-5-pro-32k-250115',
      'deepseek-r1-250120',
    ],
  },
  {
    id: 'mimo',
    name: '小米 MiMo',
    type: 'openai-chat',
    baseUrl: 'https://api.xiaomimimo.com',
    modelName: 'mimo-v2.5',
    logo: 'mimo.svg',
    modelNames: ['mimo-v2.5', 'mimo-v2.5-pro', 'mimo-v2-flash', 'mimo-v2-omni'],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    type: 'openai-chat',
    baseUrl: 'https://api.openai.com',
    modelName: 'gpt-5.2',
    logo: 'openai.png',
    modelNames: ['gpt-5.4', 'gpt-5.4-pro', 'gpt-5.2', 'gpt-5.2-pro', 'gpt-5.1', 'gpt-5'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    type: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    modelName: 'claude-sonnet-4-5',
    logo: 'anthropic.png',
    modelNames: [
      'claude-opus-4-6',
      'claude-sonnet-4-6',
      'claude-sonnet-4-5',
      'claude-haiku-4-5',
      'claude-opus-4-5',
    ],
  },
  {
    id: 'gemini',
    name: 'Gemini',
    type: 'gemini',
    baseUrl: 'https://generativelanguage.googleapis.com',
    modelName: 'gemini-2.5-flash',
    logo: 'google.png',
    modelNames: [
      'gemini-2.5-flash',
      'gemini-2.5-pro',
      'gemini-3-pro-preview',
      'gemini-3.1-pro-preview',
    ],
  },
];
